from setuptools import setup, find_packages

setup(
    name='emailviewer',
    version='0.1',
    packages=find_packages(),
    install_requires=[
        'certifi==2025.7.9',
        'charset-normalizer==3.4.2',
        'click==8.2.1',
        'colorama==0.4.6',
        'faiss-cpu==1.11.0',
        'filelock==3.18.0',
        'fsspec==2025.5.1',
        'huggingface-hub==0.33.2',
        'idna==3.10',
        'Jinja2==3.1.6',
        'joblib==1.5.1',
        'MarkupSafe==3.0.2',
        'mpmath==1.3.0',
        'networkx==3.5',
        'nltk==3.9.1',
        'numpy==2.3.1',
        'packaging==25.0',
        'pillow==11.3.0',
        'python-dotenv==1.1.1',
        'PyYAML==6.0.2',
        'regex==2024.11.6',
        'requests==2.32.4',
        'safetensors==0.5.3',
        'scikit-learn==1.7.0',
        'scipy==1.16.0',
        'sentence-transformers==5.0.0',
        'setuptools==80.9.0',
        'sympy==1.14.0',
        'threadpoolctl==3.6.0',
        'tokenizers==0.21.2',
        'torch==2.7.1',
        'tqdm==4.67.1',
        'transformers==4.53.1',
        'typing_extensions==4.14.1',
        'urllib3==2.5.0'
    ],
    entry_points={
        'console_scripts': [
            'email-viewer=main:main',  # runs main() in main.py
        ],
    },
    python_requires='>=3.8',
    author='Jayaragul',
    description='A Python CLI tool to read and search IMAP emails using semantic search.',
)
